# Site settings
title: 솔코딩의 소소한 기술블로그 Solcoding's Blog
subtitle: "Journey of [Solcoding]"
email: yejiniipark@gmail.com
description: "Make my life happy little by little"
baseurl: "/"
url: "http://solcoding.github.io"
twitter_username: "notyet"
github_username:  "samsongpark"
instagram_username: "yjpark96"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
